### ISSUE TITLE
1.16.2 support

### ISSUE THREAD

**Issue by DakirDev** [masecla22/VillagerGUIApi#1]
Hello, is it possible to add support for 1.16.2.
I get the following error message:
```[18:08:30] [Server thread/INFO]: [VillagerGUIApi] Enabling VillagerGUIApi v1.0
[18:08:30] [Server thread/WARN]: java.lang.ClassNotFoundException: masecla.villager.adapters.instances.MerchantAdapter_v1_16_R2
[18:08:30] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[18:08:30] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:08:30] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:08:30] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[18:08:30] [Server thread/WARN]:        at java.lang.Class.forName(Unknown Source)
[18:08:30] [Server thread/WARN]:        at masecla.villager.api.AdapterLoader.reflectivelyLoad(AdapterLoader.java:100)
[18:08:30] [Server thread/WARN]:        at masecla.villager.api.MainLoader.onEnable(MainLoader.java:20)
[18:08:30] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:08:30] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[18:08:30] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:08:30] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[18:08:30] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[18:08:30] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[18:08:30] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[18:08:30] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[18:08:30] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[18:08:30] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)```

**Comment by masecla22** [comment]
It is absolutely possible. I am on it right now.
Thanks for bringing it to my attention.

**Comment by masecla22** [comment]
Support for the version has been added. If any bugs remain within it, please open another issue.
