### ISSUE TITLE
class from villagerguiapi cannot be cast to class net.minecraft.server.v1_9_R2.EntityVillager

### ISSUE THREAD

**Issue by Pierronus** [masecla22/VillagerGUIApi#6]
Hello, everytime I open a Villager Gui, it goes crazy with LOTS and LOTS of errors from different plugins.
And for the same reason : 

class masecla.villager.adapters.instances.MerchantAdapter_v1_9_R2 cannot be cast to class net.minecraft.server.v1_9_R2.EntityVillager (masecla.villager.adapters.instances.MerchantAdapter_v1_9_R2 is in unnamed module of loader java.net.URLClassLoader @6a6c3afd; net.minecraft.server.v1_9_R2.EntityVillager is in unnamed module of loader 'app')

Here's an example of an error:

[23:37:12] [Server thread/WARN]: [ChestCommands] Task #78 for ChestCommands v3.1.4 generated an exception
java.lang.ClassCastException: class masecla.villager.adapters.instances.MerchantAdapter_v1_9_R2 cannot be cast to class net.minecraft.server.v1_9_R2.EntityVillager (masecla.villager.adapters.instances.MerchantAdapter_v1_9_R2 is in unnamed module of loader java.net.URLClassLoader @6a6c3afd; net.minecraft.server.v1_9_R2.EntityVillager is in unnamed module of loader 'app')
	at net.minecraft.server.v1_9_R2.InventoryMerchant.getOwner(InventoryMerchant.java:45) ~[server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftInventory.getHolder(CraftInventory.java:471) ~[server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at com.gmail.filoghost.chestcommands.task.RefreshMenusTask.run(RefreshMenusTask.java:25) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [server_debug.jar:git-Spigot-c6871e2-e1d3516]
	at java.lang.Thread.run(Thread.java:829) [?:?]

Server version : 1.9.4 spigot

Btw besides that, the API is great ! 
Thank you

**Comment by masecla22** [comment]
Did you by any chance use the /reload command?
