### ISSUE TITLE
NPE with Adapter Load on 1.19.2+

### ISSUE THREAD

**Issue by Legundo** [masecla22/VillagerGUIApi#7]
Hello,

Attempting to load a VillagerGUI in 1.19.2+ is throwing an error.

Log

```
[15:49:15 INFO]: [VillagerGUIApi] Enabling VillagerGUIApi v1.0*
[15:49:15 INFO]: [VillagerGUIApi] [STDOUT] Loading teammt/villagerguiapi/adapters/instances/MerchantAdapter_v1_19_R1.class

--- Snipped ---

Attempting to open the GUI vvv
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because the return value of "teammt.villagerguiapi.api.MainLoader.getAdapter()" is null
        at teammt.villagerguiapi.classes.VillagerInventory.open(VillagerInventory.java:51) ~[escape-1.0-SNAPSHOT.jar:?]
        at com.legundo.escape.managers.TraderManager.openTestTrader(TraderManager.java:48) ~[escape-1.0-SNAPSHOT.jar:?]
        at com.legundo.escape.EscapeCommandExecutor.onCommand(EscapeCommandExecutor.java:124) ~[escape-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

Looks like the R2 adapter isn't loading,  or it can't find version support for 1.19.2+

Pom:
```
<dependency>
            <groupId>TeamMT</groupId>
            <artifactId>VillagerGUIApi.api</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by masecla22** [comment]
Are you by any chance shading the plugin instead of loading it as a separate plugin?

**Comment by Legundo** [comment]
Heya! I do have it as a plugin, and after initially posting this it is loading an adapter, but that adapter is just failing to run. Do I need to import it as provided instead?

**EDIT:** Yep, that did it. Thanks for helping me get unstuck from my own mistakes. Considering that a lot of plugins use the maven-shade-plugin, should you include a `<scope>provided</scope>` in the readme?

**Comment by Legundo** [comment]
This can be closed
